server: "0.0.0.0:8000"
mysql:
  host: "mysql"
  port: 3306
  db: "ops-api"
  user: "root"
  password: "X3UhzF9F"
  maxIdleConns: 10
  maxOpenConns: 100
  maxLifeTime: 30
redis:
  host: "redis:6379"
  password: "o0qYcTrt"
  db: 0
oss:
  endpoint: "192.168.200.21:9000"
  accessKey: "mXBbXV8nhjmLs8Ho"
  secretKey: "Zicc4ifKsX8dGwZHwro1"
  bucketName: "ops-api"
  ssl: false