server: "0.0.0.0:8000"
mysql:
  host: "127.0.0.1"
  port: 3306
  db: "ops"
  user: "root"
  password: "p-0p-0p-0"
  maxIdleConns: 10
  maxOpenConns: 100
  maxLifeTime: 30
redis:
  host: "127.0.0.1:6379"
  password: ""
  db: 0
jwt:
  secret: "swfqezjzoqssvjck"
  expires: 6
mfa:
  enable: true
  issuer: "统一认证平台"
oss:
  endpoint: "d-minio.50yc.cn"
  accessKey: "p4gZSoyn1oP9VAqX"
  secretKey: "SblsJVWyePbuoIh1Wj5cHFmVVg31uPFA"
  bucketName: "ops"
  ssl: true
ldap:
  host: "ldap://192.168.200.13:389"
  bindUserDN: "LdapUser@wlyd.local"
  bindUserPassword: "tv47a=uB@TmC"
  searchDN: "ou=物联亿达用户,dc=wlyd,dc=local&ou=离职用户,dc=wlyd,dc=local"
sms:
  url: "https://smsapi.cn-north-4.myhuaweicloud.com:443/sms/batchSendDiffSms/v1"
  appKey: "6dW23s8dHP77OXXT808265P5gOta"
  appSecret: "GTq6BliiGoSQNYHDzH7auKy6VSmG"
  callbackUrl: "https://ops-test.50yc.cn/api/v1/sms/callback"
  verificationCode:
    sender: "8822053031549"
    templateId: "3aa3b4b4c38d4cc9b5960e31b76f5d96"
    signature: "物联亿达"
mail:
  smtpHost: "smtp.partner.outlook.cn"
  smtpPort: 587
  from: "no-reply@50yc.com"
  password: "Xab65327"
swagger: true
