info:
  contact: {}
paths:
  /api/v1/user/info:
    get:
      description: 用户相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: '{"code": 0, "msg": "获取用户信息成功", "data": }'
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - 用户管理
  /login:
    post:
      consumes:
      - application/json
      description: 用户相关接口
      parameters:
      - description: 用户名密码
        in: body
        name: user
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 0, "msg": "认证成功", "token": "用户令牌"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 用户管理
  /logout:
    post:
      consumes:
      - application/json
      description: 用户相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 0, "msg": "注销成功"}'
          schema:
            type: string
      summary: 用户注销
      tags:
      - 用户管理
swagger: "2.0"
