definitions:
  service.GroupCreate:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  service.GroupUpdate:
    properties:
      id:
        type: integer
      name:
        type: string
    required:
    - id
    - name
    type: object
  service.UserCreate:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - password
    - phone_number
    - username
    type: object
  service.UserLogin:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  service.UserPasswordUpdate:
    properties:
      id:
        type: integer
      password:
        type: string
      re_password:
        type: string
    required:
    - id
    - password
    - re_password
    type: object
  service.UserUpdate:
    properties:
      email:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      phone_number:
        type: string
    required:
    - id
    type: object
info:
  contact: {}
paths:
  /api/v1/group:
    post:
      consumes:
      - application/json
      description: 用户组相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 组信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.GroupCreate'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 0, "msg": "创建成功", "data": nil}'
          schema:
            type: string
      summary: 创建用户组
      tags:
      - 用户组管理
    put:
      description: 用户组相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.GroupUpdate'
      responses:
        "200":
          description: '{"code": 0, "msg": "更新成功", "data": nil}'
          schema:
            type: string
      summary: 用户组信息更新
      tags:
      - 用户组管理
  /api/v1/group/{id}:
    delete:
      description: 用户组相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 组ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: '{"code": 0, "msg": "删除成功", "data": nil}'
          schema:
            type: string
      summary: 删除用户组
      tags:
      - 用户组管理
  /api/v1/groups:
    get:
      description: 用户组相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分页
        in: query
        name: page
        required: true
        type: integer
      - description: 分页大小
        in: query
        name: limit
        required: true
        type: integer
      - description: 组名称
        in: query
        name: name
        type: string
      responses:
        "200":
          description: '{"code": 0, "msg": "获取列表成功", "data": []}'
          schema:
            type: string
      summary: 获取组列表
      tags:
      - 用户组管理
  /api/v1/user:
    post:
      consumes:
      - application/json
      description: 用户相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 0, "msg": "创建用户成功", "data": nil}'
          schema:
            type: string
      summary: 创建用户
      tags:
      - 用户管理
    put:
      description: 用户相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.UserUpdate'
      responses:
        "200":
          description: '{"code": 0, "msg": "更新成功", "data": nil}'
          schema:
            type: string
      summary: 用户基本信息更新
      tags:
      - 用户管理
  /api/v1/user/{id}:
    delete:
      description: 用户相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: '{"code": 0, "msg": "删除用户成功", "data": nil}'
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户管理
  /api/v1/user/avatarUpload:
    post:
      description: 用户相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 头像
        in: formData
        name: avatar
        required: true
        type: file
      responses:
        "200":
          description: '{"code": 0, "msg": "头像更新成功", "data": nil}'
          schema:
            type: string
      summary: 用户头像上传
      tags:
      - 用户管理
  /api/v1/user/info:
    get:
      description: 用户相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: '{"code": 0, "msg": "获取用户信息成功", "data": {}}'
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - 用户管理
  /api/v1/user/reset_mfa/{id}:
    put:
      description: 用户相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: '{"code": 0, "msg": "更新成功", "data": nil}'
          schema:
            type: string
      summary: 用户MFA重置
      tags:
      - 用户管理
  /api/v1/user/reset_password:
    put:
      description: 用户相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.UserPasswordUpdate'
      responses:
        "200":
          description: '{"code": 0, "msg": "更新成功", "data": nil}'
          schema:
            type: string
      summary: 用户密码更新
      tags:
      - 用户管理
  /api/v1/users:
    get:
      description: 用户相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分页
        in: query
        name: page
        required: true
        type: integer
      - description: 分页大小
        in: query
        name: limit
        required: true
        type: integer
      - description: 用户姓名
        in: query
        name: name
        type: string
      responses:
        "200":
          description: '{"code": 0, "msg": "获取用户列表成功", "data": []}'
          schema:
            type: string
      summary: 获取用户列表
      tags:
      - 用户管理
  /login:
    post:
      consumes:
      - application/json
      description: 用户相关接口
      parameters:
      - description: 用户名密码
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/service.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 0, "msg": "认证成功", "token": "用户令牌"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 用户管理
  /logout:
    post:
      description: 用户相关接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: '{"code": 0, "msg": "注销成功", "data": nil}'
          schema:
            type: string
      summary: 用户注销
      tags:
      - 用户管理
swagger: "2.0"
