version: '3'
services:
  redis:
    image: swr.cn-east-3.myhuaweicloud.com/lansefenbao/redis:5
    container_name: ops-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_REQUIRE_PASS}
    restart: always
    networks:
      - ops_network
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
  mysql:
    image: swr.cn-east-3.myhuaweicloud.com/lansefenbao/mysql:8.4.2-CST
    container_name: ops-mysql
    restart: always
    networks:
      - ops_network
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ../data.sql:/root/data.sql
      - ./data/mysql:/var/lib/mysql
  minio:
    image: swr.cn-east-3.myhuaweicloud.com/lansefenbao/minio:2024.8.26
    container_name: ops-minio
    restart: always
    networks:
      - ops_network
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_SCHEME: ${MINIO_SCHEME}
      MINIO_API_PORT_NUMBER: ${MINIO_API_PORT_NUMBER}
      MINIO_CONSOLE_PORT_NUMBER: ${MINIO_CONSOLE_PORT_NUMBER}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS}
    volumes:
      - ./data/minio:/bitnami/minio/data
  ops-api:
    depends_on:
      - mysql
      - redis
      - minio
    image: ${OPS_API_IMAGE}:${OPS_API_VERSION}
    container_name: ops-api
    restart: always
    networks:
      - ops_network
    volumes:
      - ./conf/config.yaml:/app/config/config.yaml
      - ./certs/certificate.crt:/app/certs/certificate.crt
      - ./certs/private.key:/app/certs/private.key
      - ./certs/public.key:/app/certs/public.key
  ops-web:
    image: ${OPS_WEB_IMAGE}:${OPS_WEB_VERSION}
    container_name: ops-web
    restart: always
    networks:
      - ops_network
  gateway:
    image: swr.cn-east-3.myhuaweicloud.com/lansefenbao/nginx:1.27-CST
    container_name: ops-gateway
    restart: always
    networks:
      - ops_network
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  ops_network:
    driver: bridge