kind: ConfigMap
apiVersion: v1
metadata:
  name: ops-api
data:
  config.yaml: |
    server: "0.0.0.0:8000"
    mysql:
      host: "mysql"
      port: 3306
      db: "ops-api"
      user: "root"
      password: "X3UhzF9F"
      maxIdleConns: 10
      maxOpenConns: 1000
      maxLifeTime: 30
    redis:
      host: "redis:6379"
      password: "o0qYcTrt"
      db: 0
    oss:
      endpoint: "minio:9000"
      accessKey: "mXBbXV8nhjmLs8Ho"
      secretKey: "Zicc4ifKsX8dGwZHwro1"
      bucketName: "ops-api"
      ssl: false