{{- if .Values.ingress.enabled }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ops
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.tls.hosts }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.domainName }}
      http:
        paths:
          - path: /swagger/
            pathType: Prefix
            backend:
              service:
                name: ops-api
                port:
                  number: 80
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: ops-api
                port:
                  number: 80
          - path: /p3
            pathType: Prefix
            backend:
              service:
                name: ops-api
                port:
                  number: 80
          - path: /validate
            pathType: Prefix
            backend:
              service:
                name: ops-api
                port:
                  number: 80
          - path: /.well-known/openid-configuration
            pathType: Prefix
            backend:
              service:
                name: ops-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ops-web
                port:
                  number: 80
  {{- end }}